parameters:
#    ima_demo.example.class: IMA\DemoBundle\Example

services:
#    ima_demo.example:
#        class: %ima_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
